name: Update GitHub Pages on Jupyter Notebook change

on:
  push:
    branches:
      - main
    paths:
      - '*.ipynb'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert Notebook to HTML
        run: |
          pip install nbconvert
          jupyter nbconvert --to html digit_classifier.ipynb --output-dir docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
